name: Bun CI/CD Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: server_env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Cập nhật lên v4 mới nhất

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/upload_file_server
            git pull origin main
            bun install --frozen-lockfile
            bunx prisma db push
            bun run build
            pm2 restart 'upload file server' || pm2 start dist/main.js --name 'upload file server' --interpreter ~/.bun/bin/bun
